version: '3.8'

services:
  db_dev:
    image: mysql:8.0
    container_name: db_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"
    volumes:
      - db_data_dev:/var/lib/mysql
        - ../../sql/import.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev_network

  web_dev:
    build:
      context: ../../
      dockerfile: docker/dev/web/Dockerfile
    container_name: web_dev
    depends_on:
      - db_dev
    ports:
      - "8080:80"
    volumes:
      - ../../:/var/www/html
    networks:
      - dev_network
    environment:
      - DB_HOST=db_dev
      - DB_USER=app_user
      - DB_PASSWORD=app_password
      - DB_NAME=app_db
      - ENVIRONMENT=development

volumes:
  db_data_dev:
    name: db_data_dev

networks:
  dev_network:
    name: dev_network
